import type { ToolGroupProps } from "./tool-component";
import { m } from "@/paraglide/messages";

export const tools: Array<ToolGroupProps> = [
  {
    title: m.tools_group_frontend(),
    tools: [
      {
        logo: "/tools-icons/solidjs.svg",
        title: m.tool_solidjs_title(),
        variant: "primary",
        description: m.tool_solidjs_description(),
        experience: 80,
      },
      {
        logo: "/tools-icons/tanstack-start.svg",
        title: m.tool_tanstack_start_title(),
        variant: "primary",
        description: m.tool_tanstack_start_description(),
        experience: 70,
      },
      {
        logo: "/tools-icons/tailwind-css.svg",
        title: m.tool_tailwindcss_title(),
        variant: "primary",
        description: m.tool_tailwindcss_description(),
        experience: 95,
      },
      {
        logo: "/tools-icons/react.svg",
        title: m.tool_react_title(),
        variant: "secondary",
        description: m.tool_react_description(),
        experience: 90,
      },
      {
        logo: "/tools-icons/next-js.svg",
        title: m.tool_nextjs_title(),
        variant: "secondary",
        description: m.tool_nextjs_description(),
        experience: 80,
      },
    ],
    class: "max-w-xs",
  },
  {
    title: m.tools_group_data(),
    tools: [
      {
        title: m.tool_convex_title(),
        logo: "/tools-icons/convex.svg",
        variant: "primary",
        description: m.tool_convex_description(),
        experience: 60,
      },
      {
        title: m.tool_tanstack_query_title(),
        logo: "/tools-icons/tanstack-start.svg",
        variant: "primary",
        description: m.tool_tanstack_query_description(),
        experience: 80,
      },
      {
        title: m.tool_drizzle_title(),
        logo: "/tools-icons/drizzle.svg",
        variant: "secondary",
        description: m.tool_drizzle_description(),
        experience: 80,
      },
      {
        title: m.tool_supabase_title(),
        logo: "/tools-icons/supabase.svg",
        variant: "secondary",
        description: m.tool_supabase_description(),
        experience: 55,
      },
      {
        title: m.tool_postgresql_title(),
        logo: "/tools-icons/postgresql.svg",
        variant: "secondary",
        description: m.tool_postgresql_description(),
        experience: 95,
      },
    ],
    class: "max-w-md",
  },
  {
    title: m.tools_group_languages(),
    tools: [
      {
        title: m.tool_typescript_title(),
        logo: "/tools-icons/typescript.svg",
        variant: "primary",
        description: m.tool_typescript_description(),
        experience: 95,
      },
      {
        title: m.tool_javascript_title(),
        logo: "/tools-icons/javascript.svg",
        variant: "secondary",
        description: m.tool_javascript_description(),
        experience: 60,
      },
      {
        title: m.tool_css_title(),
        logo: "/tools-icons/css.svg",
        variant: "secondary",
        description: m.tool_css_description(),
        experience: 95,
      },
      {
        title: m.tool_romanian_title(),
        logo: "/tools-icons/romanian.svg",
        variant: "language",
        description: m.tool_romanian_description(),
        experience: 100,
      },
      {
        title: m.tool_english_title(),
        logo: "/tools-icons/english.svg",
        variant: "language",
        description: m.tool_english_description(),
        experience: 95,
      },
    ],
    class: "max-w-sm",
  },
  {
    title: m.tools_group_runtime(),
    tools: [
      {
        title: m.tool_bun_title(),
        logo: "/tools-icons/bun.svg",
        variant: "primary",
        description: m.tool_bun_description(),
        experience: 80,
      },
      {
        title: m.tool_github_title(),
        logo: "/tools-icons/github.svg",
        variant: "primary",
        description: m.tool_github_description(),
        experience: 70,
      },
      {
        title: m.tool_git_title(),
        logo: "/tools-icons/git.svg",
        variant: "primary",
        description: m.tool_git_description(),
        experience: 85,
      },
      {
        title: m.tool_nodejs_title(),
        logo: "/tools-icons/node-js.svg",
        variant: "secondary",
        description: m.tool_nodejs_description(),
        experience: 80,
      },
      {
        title: m.tool_turborepo_title(),
        logo: "/tools-icons/turborepo.svg",
        variant: "secondary",
        description: m.tool_turborepo_description(),
        experience: 70,
      },
      {
        title: m.tool_pnpm_title(),
        logo: "/tools-icons/pnpm.svg",
        variant: "secondary",
        description: m.tool_pnpm_description(),
        experience: 75,
      },
      {
        title: m.tool_npm_title(),
        logo: "/tools-icons/npm.svg",
        variant: "secondary",
        description: m.tool_npm_description(),
        experience: 85,
      },
    ],
    class: "max-w-xs",
  },
  {
    title: m.tools_group_design(),
    tools: [
      {
        title: m.tool_figma_title(),
        logo: "/tools-icons/figma.svg",
        variant: "primary",
        description: m.tool_figma_description(),
        experience: 80,
      },
      {
        title: m.tool_zed_title(),
        logo: "/tools-icons/zed.svg",
        variant: "primary",
        description: m.tool_zed_description(),
        experience: 70,
      },
      {
        title: m.tool_vscode_title(),
        logo: "/tools-icons/vscode.svg",
        variant: "secondary",
        description: m.tool_vscode_description(),
        experience: 90,
      },
      {
        title: m.tool_intellij_title(),
        logo: "/tools-icons/intellij-idea.svg",
        variant: "secondary",
        description: m.tool_intellij_description(),
        experience: 70,
      },
    ],
    class: "max-w-md",
  },
];
